version: "3"

services:
  BuyABit:
    build:
      context: .
      dockerfile: BuyABit/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver-test
    environment:
        SA_PASSWORD: "MyPassword001"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"